### ISSUE TITLE
left hand category buttons / filters don't work

### ISSUE THREAD

**Issue by MarcusJT** [googlecodelabs/about#3]
I'm running Chrome 47.0.2526.35 beta-m (64-bit) and find that the category buttons on the left hand side of https://www.code-labs.io/, https://www.code-labs.io/android-dev-summit, https://www.code-labs.io/babbq-2015, http://search-codelabs.appspot.com/, etc don't do anything at all, presumably they should.

I've tried in Incognito mode to eliminate the possibility of extensions intefering but no joy.

**Comment by ebidel** [comment]
For e they scroll the page to the first card with that category. Can you provide more details? Browser version? platform? js console errors?

**Comment by MarcusJT** [comment]
Mystery solved, it was a dodgy Polymer extension that I had installed - https://chrome.google.com/webstore/detail/polymer-devtools-extensio/mmpfaamodhhlbadloaibpocmcomledcg - everything is fine again now that it's removed.

**Comment by x1ddos** [comment]
What about "I've tried in Incognito mode to eliminate the possibility of extensions intefering" part?

**Comment by MarcusJT** [comment]
Yes, I thought that was strange too, as I genuinely had tried that. I don't recall whether I'd set the extension to be enabled in Incognito mode but that's not something I usually do as I rarely use that mode. Alas I can't check now as disabling the extension resolved the issue so I uninstalled it.
